const taglib = require('taglib3');
// const file = './final/12371792_20_and_Lost_feat__ELVIRA_Original_Mix.aiff'
const file = './original/c_Elvira, Osrin - 20 and Lost feat. ELVIRA (Original Mix).aiff'
const tags = taglib.readTagsSync(file)
tags.ALBUMARTIST = ['']
tags.COMMENT= ['Purchased at Beatport.com']
tags.CONTENTGROUP = tags.LABEL
tags.DATE = [tags.DATE[0].split("-")[0]]
tags.ENCODEDBY = ['Beatport']
tags.ENCODING = ['']
tags.FILEWEBPAGE = ['\x03http://www.beatport.com/track/20-and-lost-feat-elvira-original-mix/12371792']                  // need modify
tags.INITIALKEY = ['Fmaj']
tags.ISRC = ['NLM5S1900615']
tags['ORIGINAL RELEASE DATE'] = [tags.ORIGINALDATE]
tags.ORIGINALDATE = ['']
tags.ORIGINALARTIST = ['']
tags.PUBLISHERWEBPAGE = ['\x03http://www.beatport.com/label/stmpd-rcrds/56009' ]                                        // need modify
tags.RELEASEDATE = [tags['ORIGINAL RELEASE DATE']]
taglib.writeTags(file, tags, (error, data) => console.log(error, data))
